# -*- coding: utf-8 -*-
"""官方 1.27a 对战图的野怪点(camp)组成模板，由 tools/_tmp/creep_stats.py 导出。

每项 = (组成 Counter, 出现次数权重)。出现 <3 次的组合没收录。
id 全部来自官方图实测，游戏里一定有效。"""

CAMP_TEMPLATES = [
    ({'nftr': 3, 'ngst': 1}, 18),
    ({'nwlt': 3}, 18),
    ({'nfra': 1, 'nfrl': 2, 'nfrs': 1}, 17),
    ({'nwen': 2, 'nwnr': 1}, 16),
    ({'ngnb': 1, 'ngno': 3}, 15),
    ({'nsth': 1, 'nstl': 2, 'nsts': 1}, 15),
    ({'nmfs': 2, 'nmpg': 1}, 15),
    ({'ngna': 2, 'ngnb': 1}, 14),
    ({'nfsp': 1, 'nftr': 2}, 14),
    ({'nfsp': 1, 'nftb': 2, 'ngst': 1}, 14),
    ({'ngh1': 3, 'nrvi': 1}, 12),
    ({'nitt': 3}, 12),
    ({'nnwl': 3, 'nnwq': 1, 'nnwr': 1}, 12),
    ({'uDNR': 5}, 12),
    ({'nsth': 1, 'nsts': 3}, 12),
    ({'nftr': 2}, 11),
    ({'nfrb': 1, 'nfrl': 2, 'nfrs': 1}, 11),
    ({'ncea': 2, 'ncim': 1, 'ncnk': 1}, 10),
    ({'ncim': 3}, 10),
    ({'ngna': 2, 'ngnw': 1}, 10),
    ({'ngrk': 2, 'ngst': 2}, 10),
    ({'uDNR': 4}, 10),
    ({'nmfs': 2, 'nmmu': 1}, 10),
    ({'nqbh': 2, 'nrzg': 1, 'nrzm': 2}, 9),
    ({'ngno': 2, 'ngns': 2, 'ngnv': 1}, 9),
    ({'nwlg': 1, 'nwlt': 2}, 9),
    ({'nltl': 2}, 9),
    ({'nfsh': 1, 'nftr': 2, 'nftt': 2}, 8),
    ({'nmrl': 1, 'nmrm': 1, 'nmrr': 2}, 8),
    ({'nsbm': 1, 'nsgt': 2}, 8),
    ({'uDNR': 3}, 8),
    ({'nits': 2, 'nomg': 1}, 8),
    ({'nitt': 2, 'nitw': 1}, 8),
    ({'ncen': 2, 'ncim': 1}, 8),
    ({'nbzk': 1, 'nbzw': 4}, 8),
    ({'ncer': 3}, 8),
    ({'nenc': 1, 'nenp': 2, 'nepl': 1}, 8),
    ({'ngnb': 2, 'ngns': 1, 'ngnv': 1}, 8),
    ({'nfsh': 1, 'nftb': 2, 'nggr': 1}, 8),
    ({'ngnb': 1, 'ngno': 1}, 8),
    ({'nwld': 2, 'nwlt': 1}, 8),
    ({'nstl': 1, 'nsts': 2, 'nsty': 2}, 8),
    ({'nfel': 3, 'ninf': 1}, 8),
    ({'nwwf': 3}, 8),
    ({'nftr': 3, 'nogm': 1, 'nogr': 1}, 8),
    ({'ngrk': 2, 'ngst': 1}, 8),
    ({'nfsp': 1, 'nftb': 2, 'nogl': 1}, 8),
    ({'nbzw': 2}, 7),
    ({'nfsh': 1, 'nftb': 2, 'ngst': 1}, 6),
    ({'nftb': 3, 'ngst': 1}, 6),
    ({'ngna': 1, 'ngnb': 1}, 6),
    ({'nltl': 2, 'nstw': 1}, 6),
    ({'nftb': 2, 'nftk': 1}, 6),
    ({'ngns': 3, 'ngnv': 1, 'ngnw': 2}, 6),
    ({'nfsh': 1, 'nftb': 3}, 6),
    ({'nfsh': 1, 'nftk': 1, 'nftr': 3}, 6),
    ({'nfsp': 1, 'nftb': 1, 'nftr': 2}, 6),
    ({'ngno': 1, 'ngnw': 1}, 6),
    ({'nggr': 1, 'ngst': 2}, 6),
    ({'ngst': 1, 'nogr': 2}, 6),
    ({'nogr': 2}, 6),
    ({'nbdk': 1, 'nogm': 2}, 6),
    ({'nqbh': 3, 'nstw': 1}, 6),
    ({'nqbh': 2, 'nrzb': 1}, 6),
    ({'nrzb': 2, 'nrzg': 1, 'nrzm': 2}, 6),
    ({'nqbh': 3, 'nrzm': 1}, 6),
    ({'nfra': 1, 'nfrl': 2}, 6),
    ({'nsgt': 1, 'nspr': 2}, 6),
    ({'nfrb': 1, 'nfrl': 2}, 6),
    ({'nqbh': 2, 'nrzm': 1, 'nspp': 2}, 6),
    ({'ncea': 2, 'ncen': 2}, 6),
    ({'nkog': 1, 'nkol': 1, 'nkot': 1}, 6),
    ({'nkob': 2, 'nkog': 1}, 6),
    ({'ndtb': 2, 'ndtr': 2, 'ndtw': 1}, 6),
    ({'nith': 2, 'nitr': 2, 'nitw': 1}, 6),
    ({'ngdk': 1, 'nmmu': 2}, 6),
    ({'nfrg': 1, 'nfrl': 2, 'nfrs': 1}, 6),
    ({'nmrm': 4, 'nmrr': 4}, 5),
    ({'ncim': 2, 'ncks': 1}, 5),
    ({'nftb': 2, 'nftk': 1, 'nftr': 2}, 5),
    ({'nsth': 1, 'nstl': 2, 'nsts': 2}, 5),
    ({'nmrl': 2, 'nmrr': 1, 'nthl': 2}, 5),
    ({'nowb': 3, 'nowe': 1}, 5),
    ({'nqbh': 1, 'nrzs': 2}, 5),
    ({'nrzb': 2, 'nrzm': 1, 'nrzs': 1}, 5),
    ({'nadw': 1}, 5),
    ({'nfsh': 1, 'nogm': 2, 'nomg': 1}, 4),
    ({'nfsh': 1, 'nftr': 2, 'nftt': 1}, 4),
    ({'nftb': 2, 'nomg': 1}, 4),
    ({'nfrp': 4}, 4),
    ({'nmrm': 4, 'nwnr': 1}, 4),
    ({'nogr': 3, 'nomg': 1}, 4),
    ({'ngrk': 2, 'nogr': 1}, 4),
    ({'ndtb': 2, 'ndth': 2, 'ndtw': 1}, 4),
    ({'nstl': 1, 'nsts': 2, 'nwlg': 2}, 4),
    ({'ndtb': 2, 'ndtp': 1, 'ndtt': 1}, 4),
    ({'ngnv': 1, 'ngnw': 3}, 4),
    ({'nogl': 1, 'nogm': 1, 'nomg': 1}, 4),
    ({'nfsh': 2, 'nftb': 1, 'nftk': 1}, 4),
    ({'nfsp': 1, 'nftr': 2, 'nftt': 1}, 4),
    ({'ngrw': 2, 'nltl': 3}, 4),
    ({'nfrb': 2, 'nfre': 1, 'nfrs': 1}, 4),
    ({'ngrd': 1, 'ngrw': 2, 'nltl': 2, 'nstw': 1, 'nthl': 2}, 4),
    ({'nwlg': 1, 'nwlt': 3}, 4),
    ({'nwld': 1, 'nwlt': 3}, 4),
    ({'nsat': 2, 'nstl': 1, 'nsts': 2}, 4),
    ({'nfsh': 2, 'nogl': 1, 'nomg': 2}, 4),
    ({'nith': 2, 'nitr': 4, 'nitt': 2, 'nitw': 1}, 4),
    ({'nfsp': 2, 'nftb': 1, 'nftr': 2}, 4),
    ({'nfsp': 2, 'nftb': 2}, 4),
    ({'nfsp': 1, 'nftb': 2, 'nftk': 1}, 4),
    ({'ngna': 3, 'ngnb': 1}, 4),
    ({'nfsp': 1, 'nftr': 2, 'nmrr': 2, 'nrdr': 1}, 4),
    ({'ngna': 2, 'ngno': 2, 'ngnw': 1}, 4),
    ({'nfsp': 1, 'nftr': 2, 'nomg': 1}, 4),
    ({'nftt': 2, 'nogl': 1, 'nogr': 1, 'nomg': 1}, 4),
    ({'ngnb': 2, 'ngns': 2, 'ngnv': 1}, 4),
    ({'nftr': 2, 'nogr': 1}, 4),
    ({'nfsp': 1, 'nftb': 2, 'nomg': 1}, 4),
    ({'nfsh': 1, 'nftb': 2, 'nftr': 1}, 4),
    ({'nfsp': 1, 'nftb': 2, 'nogr': 1}, 4),
    ({'nsat': 3, 'nstl': 1, 'nsty': 2}, 4),
    ({'nmrl': 3, 'nmrm': 2, 'nmrr': 2}, 4),
    ({'nltl': 1, 'nsty': 3}, 4),
    ({'ndtb': 3, 'ndth': 1}, 4),
    ({'ndtr': 2, 'ndtw': 1, 'ngrw': 2}, 4),
    ({'uDNR': 6}, 4),
    ({'ntrg': 1, 'ntrt': 2}, 4),
    ({'ntrh': 2, 'ntrt': 1}, 4),
    ({'nftr': 2, 'nogr': 2}, 4),
    ({'nftb': 2, 'nftk': 1, 'nogr': 2}, 4),
    ({'ngnb': 2, 'ngnw': 1}, 4),
    ({'ngno': 2, 'ngnv': 1, 'ngnw': 2}, 4),
    ({'ngna': 3, 'ngnv': 1}, 4),
    ({'ncea': 2, 'ncim': 2, 'ncks': 1}, 4),
    ({'nowb': 3, 'nowk': 1}, 4),
    ({'ngns': 2, 'ngnw': 1}, 4),
    ({'nass': 2, 'nwzd': 1}, 4),
    ({'nwzd': 1, 'nwzg': 2}, 4),
    ({'nsbm': 1, 'nssp': 3}, 4),
    ({'ngdk': 2, 'ngrd': 1}, 4),
    ({'nfrl': 3}, 4),
    ({'nsat': 1, 'nstl': 1, 'nsts': 3, 'nsty': 2}, 4),
    ({'nadk': 1, 'nomg': 3}, 4),
    ({'ngnb': 1, 'ngns': 2, 'ngnv': 1}, 4),
    ({'nfsp': 2, 'nftr': 3, 'ngst': 1}, 4),
    ({'nftb': 2, 'nogl': 1, 'nomg': 1}, 4),
    ({'ngns': 2, 'ngnv': 1, 'ngnw': 2}, 4),
    ({'nfsp': 2, 'nftb': 2, 'nogl': 1}, 4),
    ({'nftr': 3, 'nftt': 2}, 4),
    ({'ngst': 3}, 4),
    ({'nftb': 2, 'ngst': 1}, 4),
    ({'nfsp': 1, 'nftr': 2, 'ngst': 1}, 4),
    ({'nltl': 2, 'nthl': 2}, 4),
    ({'ngdk': 2, 'ngrw': 2}, 4),
    ({'nith': 2, 'nits': 2, 'nnwa': 2}, 4),
    ({'ngna': 3, 'ngns': 2, 'ngst': 1}, 4),
    ({'nsgt': 1, 'nspr': 1, 'nssp': 2}, 3),
    ({'ngrd': 1, 'ngrw': 5}, 3),
    ({'ndth': 1, 'ndtt': 3}, 3),
    ({'nrzm': 1, 'nrzt': 2, 'nspp': 2}, 3),
    ({'nhrh': 1, 'nhrq': 1, 'nhrr': 3}, 3),
    ({'nqbh': 2, 'nrzg': 1, 'nrzs': 3}, 3),
    ({'ncen': 2, 'ncks': 1}, 3),
    ({'nbzd': 1, 'ncea': 2, 'ncen': 3}, 3),
    ({'nqbh': 2, 'nrzm': 1, 'nrzs': 2}, 3),
    ({'ncea': 1, 'ncer': 1}, 3),
    ({'ncea': 1, 'ncer': 2}, 3),
    ({'nfel': 2, 'ninf': 1}, 3),
    ({'nmfs': 2, 'nmmu': 1, 'nmpg': 1}, 3),
    ({'nmfs': 3, 'nmmu': 1, 'nmpg': 1}, 3),
    ({'nftb': 1, 'ngno': 2}, 3),
    ({'nogr': 1, 'nomg': 1}, 3),
    ({'nogm': 1, 'nogr': 2}, 3),
    ({'nftr': 2, 'nogm': 2, 'nomg': 1}, 3),
    ({'nbzd': 1, 'nbzk': 4}, 3),
    ({'nenp': 3, 'nepl': 1}, 3),
    ({'nwld': 1, 'nwlg': 2}, 3),
    ({'ndth': 2, 'ndtt': 2}, 3),
    ({'nfrb': 2, 'nfrg': 1, 'nfrl': 2, 'nfrs': 1}, 3),
    ({'ndtb': 1, 'ndth': 2, 'ndtw': 1}, 3),
    ({'nltl': 3, 'nstw': 1, 'nthl': 2}, 3),
    ({'nadr': 1}, 3),
]
