# -*- coding: utf-8 -*-
"""地图风格（tileset）表 —— 全项目唯一数据源。

纹理表 = 游戏 TerrainArt/Terrain.slk 按行序（行序 = w3e 纹理索引序，
Ldrt/Ldro/Ldrg/Lrok/Lgrs/Lgrd = 0~5 已实证）；跨风格映射用 convertTo 列。
树/雇佣兵/野怪池 = 45 张官方 1.27a 对战图实测
（tools/_tmp/tileset_map_stats.py，见 style_map_stats.txt）。

⚠ 一张图只能一种风格（w3e 头一个 tileset 字母）；多选 = 生成时随机抽一。
由 tools/_tmp/gen_tilesets.py 生成。"""

STYLES = {
    "L": {
        "name": "洛丹伦的夏天",
        "tree": "LTlt",
        "merc": "nmer",
        "textures": ['Ldrt', 'Ldro', 'Ldrg', 'Lrok', 'Lgrs', 'Lgrd'],
        "cliffs": ['CLdi', 'CLgr'],
        "pool": ['nfsh', 'nfsp', 'nftb', 'nftk', 'nftr', 'nftt', 'nggr', 'ngna', 'ngnb', 'ngno', 'ngns', 'ngnv', 'ngnw', 'ngrk', 'ngst', 'nogl', 'nogm', 'nogr', 'nomg', 'nrdk', 'nrdr', 'nrwm', 'ntrg', 'ntrh', 'ntrt'],
    },
    "W": {
        "name": "洛丹伦的冬天",
        "tree": "WTtw",
        "merc": "nmr3",
        "textures": ['Wdrt', 'Wdro', 'Wsng', 'Wrok', 'Wgrs', 'Wsnw'],
        "cliffs": ['CWgr', 'CWsn'],
        "pool": ['nadk', 'nadr', 'nadw', 'nfsh', 'nfsp', 'nftb', 'nftk', 'nftr', 'nftt', 'nggr', 'ngna', 'ngnb', 'ngno', 'ngns', 'ngnv', 'ngnw', 'ngrk', 'ngst', 'nith', 'nitr', 'nits', 'nitt', 'nitw', 'nogl', 'nogm', 'nogr', 'nomg'],
    },
    "F": {
        "name": "洛丹伦的秋天",
        "tree": "FTtw",
        "merc": "nmer",
        "textures": ['Fdrt', 'Fdro', 'Fdrg', 'Frok', 'Fgrs', 'Fgrd'],
        "cliffs": ['CFdi', 'CFgr'],
        "pool": ['nbdk', 'nbwm', 'nfsp', 'nftb', 'nftk', 'nftr', 'nggr', 'ngna', 'ngnb', 'ngns', 'ngnv', 'ngnw', 'ngst', 'nogl', 'nogm', 'nogr', 'nomg'],
    },
    "A": {
        "name": "灰谷",
        "tree": "ATtr",
        "merc": "nmr5",
        "textures": ['Adrt', 'Adrd', 'Agrs', 'Arck', 'Agrd', 'Avin', 'Adrg', 'Alvd'],
        "cliffs": ['CAgr', 'CAdi'],
        "pool": ['ndtb', 'ndth', 'ndtp', 'ndtr', 'ndtt', 'ndtw', 'nfra', 'nfrb', 'nfre', 'nfrl', 'nfrs', 'ngdk', 'ngrd', 'ngrw', 'nltl', 'nsat', 'nsbm', 'nsgt', 'nspr', 'nssp', 'nsth', 'nstl', 'nsts', 'nstw', 'nsty', 'nthl', 'nwld', 'nwlg', 'nwlt'],
    },
    "B": {
        "name": "荒地",
        "tree": "BTtw",
        "merc": "nmr4",
        "textures": ['Bdrt', 'Bdrh', 'Bdrr', 'Bdrg', 'Bdsr', 'Bdsd', 'Bflr', 'Bgrr'],
        "cliffs": ['CBde', 'CBgr'],
        "pool": ['nbzd', 'nbzk', 'nbzw', 'ncea', 'ncen', 'ncer', 'ncim', 'ncks', 'ncnk', 'nhrh', 'nhrq', 'nhrr', 'nhrw', 'nltl', 'nowb', 'nowe', 'nowk', 'nqbh', 'nrzb', 'nrzg', 'nrzm', 'nrzs', 'nrzt', 'nspp', 'nstw', 'nthl'],
    },
    "C": {
        "name": "费尔伍德",
        "tree": "CTtr",
        "merc": "nmr6",
        "textures": ['Cdrt', 'Cdrd', 'Cpos', 'Crck', 'Cvin', 'Cgrs', 'Clvg', 'CAc2'],
        "cliffs": ['CCgr', 'CCdi'],
        "pool": ['nbal', 'nenc', 'nenp', 'nepl', 'nfel', 'nfrb', 'nfre', 'nfrg', 'nfrl', 'nfrs', 'ngdk', 'ngrd', 'ngrw', 'ninf', 'nltl', 'nmfs', 'nmmu', 'nmpg', 'nsbm', 'nsgt', 'nssp', 'nsth', 'nstl', 'nsts', 'nthl'],
    },
    "N": {
        "name": "诺森德",
        "tree": "WTst",
        "merc": "nmr7",
        "textures": ['Ndrt', 'Ndrd', 'Nrck', 'Ngrs', 'Nice', 'Nsnw', 'Nsnr'],
        "cliffs": ['CNdi', 'CNsn'],
        "pool": ['nadk', 'nadw', 'nfrp', 'ngh1', 'nith', 'nitr', 'nits', 'nitt', 'nitw', 'nnwa', 'nnwl', 'nnwq', 'nnwr', 'nrvi', 'nwen', 'nwnr', 'nwns', 'nwwf'],
    },
    "Y": {
        "name": "城市",
        "tree": "LTlt",
        "merc": "nmr8",
        "textures": ['Ydrt', 'Ydtr', 'Yblm', 'Ybtl', 'Ysqd', 'Yrtl', 'Ygsb', 'Yhdg', 'Ywmb'],
        "cliffs": ['CYdi', 'CYsq'],
        "pool": ['nass', 'nbld', 'nbrg', 'nenf', 'ngrk', 'ngst', 'nkob', 'nkog', 'nkol', 'nkot', 'nrog', 'nwzd', 'nwzg', 'nwzr'],
    },
}

# tileID → {目标风格字母: tileID}（Terrain.slk convertTo 列，语义等价纹理）
CONVERT = {
    "Adrd": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdsd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vdrr', 'Q': 'Qdrr', 'X': 'Xdtr', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zdtr', 'I': 'Idtr', 'O': 'Odtr'},
    "Adrt": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "Agrs": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'C': 'Cgrs', 'N': 'Ngrs', 'Y': 'Yhdg', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofsl'},
    "Adrg": {'L': 'Ldrg', 'F': 'Fdrg', 'W': 'Wsng', 'B': 'Bdrg', 'C': 'Cpos', 'N': 'Nice', 'Y': 'Ygsb', 'V': 'Vgrt', 'Q': 'Qgrt', 'X': 'Xgsb', 'D': 'Drds', 'G': 'Grds', 'Z': 'Zdrg', 'I': 'Idtr', 'O': 'Ofsl'},
    "Adrt": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "Agrd": {'L': 'Lgrd', 'F': 'Fgrd', 'W': 'Wsnw', 'B': 'Bdrg', 'C': 'Cpos', 'N': 'Ngrs', 'Y': 'Ygsb', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xgsb', 'D': 'Dgrs', 'G': 'Ggrs', 'Z': 'Zvin', 'I': 'Isnw', 'O': 'Ofst'},
    "Agrs": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'C': 'Cgrs', 'N': 'Ngrs', 'Y': 'Yhdg', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofsl'},
    "Alvd": {'L': 'Lgrd', 'F': 'Fgrd', 'W': 'Wsnw', 'B': 'Bdrg', 'C': 'Clvg', 'N': 'Nice', 'Y': 'Ygsb', 'V': 'Vgrt', 'Q': 'Qgrt', 'X': 'Xgsb', 'D': 'Dlvc', 'G': 'Glvc', 'Z': 'Zvin', 'I': 'Idki', 'O': 'Ofst'},
    "Arck": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ybtl', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xbtl', 'D': 'Ddkr', 'G': 'Gdkr', 'Z': 'Zbkl', 'I': 'Irbk', 'O': 'Ofst'},
    "Avin": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bdrr', 'C': 'Cvin', 'N': 'Nsnr', 'Y': 'Yrtl', 'V': 'Vcrp', 'Q': 'Qcrp', 'X': 'Xrtl', 'D': 'Dlav', 'G': 'Glav', 'Z': 'Zvin', 'I': 'Iice', 'O': 'Ofst'},
    "Bdrg": {'L': 'Ldrg', 'F': 'Fdrg', 'W': 'Wsng', 'A': 'Adrg', 'C': 'Clvg', 'N': 'Nice', 'Y': 'Ygsb', 'V': 'Vgrt', 'Q': 'Qgrt', 'X': 'Xgsb', 'D': 'Dgrs', 'G': 'Ggrs', 'Z': 'Zdrg', 'I': 'Idtr', 'O': 'Ofsl'},
    "Bdrh": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vdrr', 'Q': 'Qdrr', 'X': 'Xdtr', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zdtr', 'I': 'Idtr', 'O': 'Odtr'},
    "Bdrr": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'A': 'Avin', 'C': 'Cvin', 'N': 'Nsnr', 'Y': 'Ybtl', 'V': 'Vcbp', 'Q': 'Qcbp', 'X': 'Xbtl', 'D': 'Drds', 'G': 'Grds', 'Z': 'Zbks', 'I': 'Ibkb', 'O': 'Osmb'},
    "Bdrt": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "Bdsd": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vdrr', 'Q': 'Qdrr', 'X': 'Xdtr', 'D': 'Dlav', 'G': 'Glav', 'Z': 'Zsan', 'I': 'Idki', 'O': 'Ofst'},
    "Bdsr": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zsan', 'I': 'Iice', 'O': 'Ofst'},
    "Bflr": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ywmb', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xwmb', 'D': 'Ddkr', 'G': 'Gdkr', 'Z': 'Zbkl', 'I': 'Irbk', 'O': 'Ofst'},
    "Bgrr": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'A': 'Agrs', 'C': 'Cgrs', 'N': 'Ngrs', 'Y': 'Yhdg', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dlvc', 'G': 'Glvc', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofsl'},
    "CAc2": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt', 'A': 'Adrt'},
    "Cdrd": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdsd', 'A': 'Adrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vdrr', 'Q': 'Qdrr', 'X': 'Xdtr', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zdtr', 'I': 'Idtr', 'O': 'Odtr'},
    "Cdrt": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "Cgrs": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'N': 'Ngrs', 'Y': 'Yhdg', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dgrs', 'G': 'Ggrs', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofsl'},
    "Clvg": {'L': 'Lgrd', 'F': 'Fgrd', 'W': 'Wsnw', 'B': 'Bdrg', 'A': 'Alvd', 'N': 'Nsnw', 'Y': 'Ygsb', 'V': 'Vgrt', 'Q': 'Qgrt', 'X': 'Xgsb', 'D': 'Dlvc', 'G': 'Glvc', 'Z': 'Zvin', 'I': 'Idki', 'O': 'Ofsl'},
    "Cpos": {'L': 'Ldrg', 'F': 'Fdrg', 'W': 'Wsng', 'B': 'Bdrg', 'A': 'Adrg', 'N': 'Nice', 'Y': 'Ygsb', 'V': 'Vgrt', 'Q': 'Qgrt', 'X': 'Xgsb', 'D': 'Drds', 'G': 'Grds', 'Z': 'Zsan', 'I': 'Iice', 'O': 'Ofsl'},
    "Crck": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'N': 'Nrck', 'Y': 'Ybtl', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xbtl', 'D': 'Ddkr', 'G': 'Gdkr', 'Z': 'Zbkl', 'I': 'Irbk', 'O': 'Ofst'},
    "Cvin": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bdrr', 'A': 'Avin', 'N': 'Nsnr', 'Y': 'Yrtl', 'V': 'Vcrp', 'Q': 'Qcrp', 'X': 'Xrtl', 'D': 'Dlav', 'G': 'Glav', 'Z': 'Zvin', 'I': 'Idki', 'O': 'Ofsl'},
    "Dbrk": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdsd', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'V': 'Vdrr', 'Y': 'Ydtr', 'Q': 'Qdrr', 'X': 'Xdtr', 'G': 'Gbrk', 'Z': 'Zbks', 'I': 'Ibkb', 'O': 'Osmb'},
    "Ddkr": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ybtl', 'V': 'Vrck', 'X': 'Xbtl', 'Q': 'Qrck', 'G': 'Gdkr', 'Z': 'Zbkl', 'I': 'Ibsq', 'O': 'Olgb'},
    "Ddrt": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'Y': 'Ydrt', 'X': 'Xdrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "Dgrs": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Cgrs', 'N': 'Nrck', 'V': 'Vrck', 'Q': 'Qrck', 'Y': 'Ywmb', 'X': 'Xwmb', 'G': 'Ggrs', 'Z': 'Ztil', 'I': 'Itbk', 'O': 'Ofst'},
    "Dlav": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bdsd', 'A': 'Avin', 'C': 'Cvin', 'N': 'Nrck', 'Y': 'Yhdg', 'V': 'Vcrp', 'Q': 'Qcrp', 'X': 'Xhdg', 'G': 'Glav', 'I': 'Iice', 'O': 'Ofst'},
    "Dlvc": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bgrr', 'A': 'Alvd', 'C': 'Clvg', 'N': 'Nrck', 'Y': 'Yhdg', 'V': 'Vcrp', 'Q': 'Qcrp', 'X': 'Xhdg', 'G': 'Glvc', 'Z': 'Zsan', 'I': 'Idki', 'O': 'Ofst'},
    "Drds": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdrr', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vcbp', 'Q': 'Qcbp', 'X': 'Xdtr', 'G': 'Grds', 'Z': 'Zbkl', 'I': 'Idtr', 'O': 'Ofsl'},
    "Dsqd": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'Y': 'Ysqd', 'X': 'Xsqd', 'G': 'Gsqd', 'Z': 'Zbkl', 'I': 'Itbk', 'O': 'Osqt'},
    "Fdrg": {'L': 'Ldrg', 'W': 'Wsng', 'B': 'Bdrr', 'C': 'Cpos', 'N': 'Ngrs', 'Y': 'Ygsb', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xgsb', 'D': 'Dgrs', 'G': 'Ggrs', 'Z': 'Zdrg', 'I': 'Idki', 'O': 'Ofsl', 'A': 'Adrg'},
    "Fdro": {'L': 'Ldro', 'W': 'Wdro', 'B': 'Bdsd', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vdrr', 'Q': 'Qdrr', 'X': 'Xdtr', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zdtr', 'I': 'Idtr', 'O': 'Odtr'},
    "Fdrt": {'L': 'Ldrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "Fgrd": {'L': 'Lgrd', 'W': 'Wsnw', 'B': 'Bdrg', 'A': 'Agrd', 'C': 'Clvg', 'N': 'Nice', 'Y': 'Ygsb', 'V': 'Vgrt', 'Q': 'Qgrt', 'X': 'Xgsb', 'D': 'Dlav', 'G': 'Glav', 'Z': 'Zvin', 'I': 'Iice', 'O': 'Ofst'},
    "Fgrs": {'L': 'Lgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'C': 'Cgrs', 'N': 'Nsnw', 'Y': 'Ygsb', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dsqd', 'G': 'Gsqd', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofsl'},
    "Frok": {'L': 'Lrok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ybtl', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xbtl', 'D': 'Ddkr', 'G': 'Gdkr', 'Z': 'Zbkl', 'I': 'Irbk', 'O': 'Ofst'},
    "Gbrk": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdsd', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'V': 'Vdrr', 'Y': 'Ydtr', 'Q': 'Qdrr', 'X': 'Xdtr', 'D': 'Dbrk', 'Z': 'Zbks', 'I': 'Ibkb', 'O': 'Osmb'},
    "Gdkr": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ybtl', 'V': 'Vrck', 'X': 'Xbtl', 'Q': 'Qrck', 'D': 'Ddkr', 'Z': 'Zbkl', 'I': 'Ibsq', 'O': 'Olgb'},
    "Gdrt": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'Y': 'Ydrt', 'X': 'Xdrt', 'D': 'Ddrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "Ggrs": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Cgrs', 'N': 'Nrck', 'V': 'Vrck', 'Q': 'Qrck', 'Y': 'Ywmb', 'X': 'Xwmb', 'D': 'Dgrs', 'Z': 'Ztil', 'I': 'Itbk', 'O': 'Ofst'},
    "Glav": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bdsd', 'A': 'Avin', 'C': 'Cvin', 'N': 'Nrck', 'Y': 'Yhdg', 'V': 'Vcrp', 'Q': 'Qcrp', 'X': 'Xhdg', 'D': 'Dlav', 'Z': 'Zsan', 'I': 'Iice', 'O': 'Ofst'},
    "Glvc": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bgrr', 'A': 'Alvd', 'C': 'Clvg', 'N': 'Nrck', 'Y': 'Yhdg', 'V': 'Vcrp', 'Q': 'Qcrp', 'X': 'Xhdg', 'D': 'Dlvc', 'Z': 'Zsan', 'I': 'Idki', 'O': 'Ofst'},
    "Grds": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdrr', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vcbp', 'Q': 'Qcbp', 'X': 'Xdtr', 'D': 'Drds', 'Z': 'Zbkl', 'I': 'Idtr', 'O': 'Ofsl'},
    "Gsqd": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'Y': 'Ysqd', 'X': 'Xsqd', 'D': 'Dsqd', 'Z': 'Zbkl', 'I': 'Itbk', 'O': 'Osqt'},
    "Ibkb": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bdrr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ybtl', 'V': 'Vcbp', 'Q': 'Qcbp', 'X': 'Xbtl', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zbks', 'O': 'Osmb'},
    "Ibsq": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Yblm', 'V': 'Vstp', 'Q': 'Qstp', 'X': 'Xblm', 'D': 'Ddkr', 'G': 'Gdkr', 'Z': 'Ztil', 'O': 'Odkt'},
    "Idki": {'L': 'Ldrg', 'F': 'Fdrg', 'W': 'Wsng', 'B': 'Bdsd', 'A': 'Alvd', 'C': 'Cvin', 'N': 'Ngrs', 'Y': 'Yhdg', 'V': 'Vcrp', 'Q': 'Qcrp', 'X': 'Xhdg', 'D': 'Dlvc', 'G': 'Glvc', 'Z': 'Zvin', 'O': 'Ofst'},
    "Idrt": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdrt', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'O': 'Odrt'},
    "Idtr": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdrh', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vdrr', 'Q': 'Qdrr', 'X': 'Xdtr', 'D': 'Drds', 'G': 'Grds', 'Z': 'Zdtr', 'O': 'Odtr'},
    "Iice": {'L': 'Lgrd', 'F': 'Fgrd', 'W': 'Wgrs', 'B': 'Bdsr', 'A': 'Avin', 'C': 'Cpos', 'N': 'Nice', 'Y': 'Yhdg', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dlav', 'G': 'Glav', 'Z': 'Zsan', 'O': 'Ofst'},
    "Irbk": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ysqd', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xsqd', 'D': 'Ddkr', 'G': 'Gdkr', 'Z': 'Zbkl', 'O': 'Olgb'},
    "Isnw": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wsnw', 'B': 'Bgrr', 'A': 'Agrs', 'C': 'Cgrs', 'N': 'Nsnw', 'Y': 'Ygsb', 'V': 'Vgrt', 'Q': 'Qgrt', 'X': 'Xgsb', 'D': 'Dgrs', 'G': 'Ggrs', 'Z': 'Zgrs', 'O': 'Ofsl'},
    "Itbk": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Yrtl', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xrtl', 'D': 'Dsqd', 'G': 'Gsqd', 'Z': 'Ztil', 'O': 'Osqt'},
    "Jblm": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bdrr', 'A': 'Avin', 'C': 'Cvin', 'N': 'Nrck', 'Y': 'Yblm', 'V': 'Vstp', 'Q': 'Qstp', 'X': 'Xblm', 'D': 'Drds', 'G': 'Grds', 'Z': 'Ztil', 'I': 'Ibsq'},
    "Jbtl": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ybtl', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xbtl', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zbks', 'I': 'Ibkb'},
    "Jdrt": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'Y': 'Ydrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt'},
    "Jdtr": {'L': 'Ldtr', 'F': 'Fdtr', 'W': 'Wdtr', 'B': 'Bdrh', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vdrr', 'Q': 'Qdrr', 'X': 'Xdtr', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zdrg', 'I': 'Idtr'},
    "Jgsb": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'N': 'Nsnw', 'Y': 'Ygsb', 'C': 'Cgrs', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xgsb', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zgrs', 'I': 'Isnw'},
    "Jhdg": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'N': 'Nice', 'Y': 'Yhdg', 'C': 'Cgrs', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zsan', 'I': 'Iice'},
    "Jrtl": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Yrtl', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xrtl', 'D': 'Dsqd', 'G': 'Gsqd', 'Z': 'Ztil', 'I': 'Itbk'},
    "Jsqd": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Nsnr', 'Y': 'Ysqd', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xsqd', 'D': 'Dsqd', 'G': 'Gsqd', 'Z': 'Zbkl', 'I': 'Irbk'},
    "Jwmb": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ywmb', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xwmb', 'D': 'Dgrs', 'G': 'Ggrs', 'Z': 'Ztil', 'I': 'Ibsq'},
    "Kdkt": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Yblm', 'V': 'Vstp', 'Q': 'Qstp', 'X': 'Xblm', 'D': 'Ddkr', 'G': 'Gdkr', 'Z': 'Ztil', 'I': 'Ibsq', 'O': 'Odkt'},
    "Kdrt": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdrt', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "Kdtr": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdrh', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vdrr', 'Q': 'Qdrr', 'X': 'Xdtr', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdtr', 'I': 'Idtr', 'O': 'Odtr'},
    "Kfsl": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'C': 'Cgrs', 'N': 'Ngrs', 'Y': 'Ygsb', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xgsb', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrg', 'I': 'Iice', 'O': 'Ofsl'},
    "Kfst": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdrr', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vcbp', 'Q': 'Qcbp', 'X': 'Xdtr', 'D': 'Drds', 'G': 'Grds', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofst'},
    "Klgb": {'L': 'Lrok', 'F': 'Frck', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'N': 'Nrck', 'Y': 'Yrtl', 'V': 'Vstp', 'Q': 'Qstp', 'X': 'Xrtl', 'D': 'Ddkr', 'G': 'Gdkr', 'Z': 'Zbkl', 'I': 'Irbk', 'O': 'Olgb'},
    "Ksmb": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ybtl', 'V': 'Vcbp', 'Q': 'Qcbp', 'X': 'Xbtl', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zbks', 'I': 'Ibkb', 'O': 'Osmb'},
    "Ksqt": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ysqd', 'V': 'Vsqd', 'Q': 'Qcrp', 'D': 'Dgrs', 'G': 'Ggrs', 'Z': 'Zbkl', 'I': 'Itbk', 'O': 'Osqt'},
    "Ldrg": {'F': 'Fdrg', 'W': 'Wsng', 'B': 'Bdrr', 'C': 'Cpos', 'N': 'Ngrs', 'Y': 'Ygsb', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xgsb', 'D': 'Dgrs', 'G': 'Ggrs', 'Z': 'Zdrg', 'I': 'Idki', 'O': 'Ofsl', 'A': 'Adrg'},
    "Ldro": {'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdsd', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vdrr', 'Q': 'Qdrr', 'X': 'Xdtr', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zdtr', 'I': 'Idtr', 'O': 'Odtr'},
    "Ldrt": {'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "Lgrd": {'F': 'Fgrd', 'W': 'Wsnw', 'B': 'Bdrg', 'A': 'Agrd', 'C': 'Clvg', 'N': 'Nice', 'Y': 'Ygsb', 'V': 'Vgrt', 'Q': 'Qgrt', 'X': 'Xgsb', 'D': 'Dlav', 'G': 'Glav', 'Z': 'Zvin', 'I': 'Iice', 'O': 'Ofst'},
    "Lgrs": {'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'C': 'Cgrs', 'N': 'Nsnw', 'Y': 'Ygsb', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dsqd', 'G': 'Gsqd', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofsl'},
    "Lrok": {'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ybtl', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xbtl', 'D': 'Ddkr', 'G': 'Gdkr', 'Z': 'Zbkl', 'I': 'Irbk', 'O': 'Ofst'},
    "Ndrd": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdsd', 'A': 'Adrd', 'C': 'Cdrd', 'Y': 'Ydtr', 'V': 'Vdrr', 'Q': 'Qdrr', 'X': 'Xdtr', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zdtr', 'I': 'Idtr', 'O': 'Odtr'},
    "Ndrt": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "Ngrs": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'C': 'Cgrs', 'Y': 'Yhdg', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zgrs', 'I': 'Idki', 'O': 'Ofsl'},
    "Nice": {'L': 'Lgrd', 'F': 'Fgrd', 'W': 'Wsnw', 'B': 'Bdrg', 'A': 'Agrd', 'C': 'Cpos', 'Y': 'Ygsb', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xgsb', 'D': 'Dgrs', 'G': 'Ggrs', 'Z': 'Zvin', 'I': 'Iice', 'O': 'Ofst'},
    "Nrck": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'Y': 'Ybtl', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xbtl', 'D': 'Ddkr', 'G': 'Gdkr', 'Z': 'Zbkl', 'I': 'Irbk', 'O': 'Ofst'},
    "Nsnr": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bdrr', 'A': 'Avin', 'C': 'Cvin', 'Y': 'Ysqd', 'V': 'Vstp', 'Q': 'Qstp', 'X': 'Xsqd', 'D': 'Dlvc', 'G': 'Glvc', 'Z': 'Zdrg', 'I': 'Idki', 'O': 'Osmb'},
    "Nsnw": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'C': 'Clvg', 'Y': 'Yhdg', 'V': 'Vgrt', 'Q': 'Qgrt', 'X': 'Xhdg', 'D': 'Dlav', 'G': 'Glav', 'Z': 'Zsan', 'I': 'Isnw', 'O': 'Ofst'},
    "Oaby": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'C': 'Cgrs', 'N': 'Ngrs', 'Y': 'Ygsb', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xgsb', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrg', 'I': 'Iice', 'K': 'Kfsl'},
    "Odrt": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdrt', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'K': 'Kdrt'},
    "Odtr": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdrh', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vdrr', 'Q': 'Qdrr', 'X': 'Xdtr', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdtr', 'I': 'Idtr', 'K': 'Kdtr'},
    "Ofsl": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'C': 'Cgrs', 'N': 'Ngrs', 'Y': 'Ygsb', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xgsb', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrg', 'I': 'Iice', 'K': 'Kfsl'},
    "Ofst": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdrr', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vcbp', 'Q': 'Qcbp', 'X': 'Xdtr', 'D': 'Drds', 'G': 'Grds', 'Z': 'Zgrs', 'I': 'Isnw', 'K': 'Kfst'},
    "Olgb": {'L': 'Lrok', 'F': 'Frck', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'N': 'Nrck', 'Y': 'Yrtl', 'V': 'Vstp', 'Q': 'Qstp', 'X': 'Xrtl', 'D': 'Ddkr', 'G': 'Gdkr', 'Z': 'Zbkl', 'I': 'Irbk', 'K': 'Klgb'},
    "Orok": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'N': 'Nrck', 'Y': 'Ybtl', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xbtl', 'D': 'Ddkr', 'G': 'Gdkr', 'C': 'Crck', 'Z': 'Zbkl', 'I': 'Irbk', 'K': 'Krck'},
    "Osmb": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ybtl', 'V': 'Vcbp', 'Q': 'Qcbp', 'X': 'Xbtl', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zbks', 'I': 'Ibkb', 'K': 'Ksmb'},
    "Qcbp": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdsd', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vcbp', 'X': 'Xdtr', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zbks', 'I': 'Ibkb', 'O': 'Osmb'},
    "Qcrp": {'L': 'Ldrg', 'F': 'Fdrg', 'W': 'Wsng', 'B': 'Bdrr', 'A': 'Adrg', 'C': 'Cvin', 'N': 'Nsnw', 'Y': 'Yhdg', 'V': 'Vcrp', 'X': 'Xhdg', 'D': 'Dlvc', 'G': 'Glvc', 'Z': 'Zsan', 'I': 'Idki', 'O': 'Osqt'},
    "Qdrr": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdsd', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vdrr', 'X': 'Xdtr', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zdtr', 'I': 'Idtr', 'O': 'Odtr'},
    "Qdrt": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "Qgrs": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'N': 'Ngrs', 'C': 'Cgrs', 'V': 'Vgrs', 'X': 'Xhdg', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zdrg', 'I': 'Iice', 'O': 'Ofsl'},
    "Qgrt": {'L': 'Lgrd', 'F': 'Fgrd', 'W': 'Wsnw', 'B': 'Bdrg', 'A': 'Agrd', 'C': 'Clvg', 'N': 'Nice', 'Y': 'Ygsb', 'V': 'Vgrt', 'X': 'Xgsb', 'D': 'Dlav', 'G': 'Glav', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofst'},
    "Qrck": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ybtl', 'V': 'Vrck', 'X': 'Xbtl', 'D': 'Ddkr', 'G': 'Gdkr', 'Z': 'Zbkl', 'I': 'Irbk', 'O': 'Ofst'},
    "Qstp": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nsnr', 'Y': 'Ywmb', 'V': 'Vstp', 'X': 'Xwmb', 'D': 'Drds', 'G': 'Grds', 'Z': 'Zbkl', 'I': 'Ibsq', 'O': 'Olgb'},
    "Vcbp": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdsd', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'Q': 'Qcbp', 'X': 'Xdtr', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zbks', 'I': 'Ibkb', 'O': 'Osmb'},
    "Vcrp": {'L': 'Ldrg', 'F': 'Fdrg', 'W': 'Wsng', 'B': 'Bdrr', 'A': 'Adrg', 'C': 'Cvin', 'N': 'Nrck', 'Y': 'Yhdg', 'Q': 'Qcrp', 'X': 'Xhdg', 'D': 'Dlvc', 'G': 'Glvc', 'Z': 'Zsan', 'I': 'Idki', 'O': 'Osqt'},
    "Vdrr": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdsd', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'Q': 'Qdrr', 'X': 'Xdtr', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zdtr', 'I': 'Idtr', 'O': 'Odtr'},
    "Vdrt": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "Vgrs": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'N': 'Ngrs', 'C': 'Cgrs', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zdrg', 'I': 'Iice', 'O': 'Ofsl'},
    "Vgrt": {'L': 'Lgrd', 'F': 'Fgrd', 'W': 'Wsnw', 'B': 'Bdrg', 'A': 'Agrd', 'C': 'Clvg', 'N': 'Nice', 'Y': 'Ygsb', 'Q': 'Qgrt', 'X': 'Xgsb', 'D': 'Dlav', 'G': 'Glav', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofst'},
    "Vrck": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ybtl', 'Q': 'Qrck', 'X': 'Xbtl', 'D': 'Ddkr', 'G': 'Gdkr', 'Z': 'Zbkl', 'I': 'Irbk', 'O': 'Ofst'},
    "Vstp": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nsnw', 'Y': 'Ywmb', 'Q': 'Qstp', 'X': 'Xwmb', 'D': 'Drds', 'G': 'Grds', 'Z': 'Zbkl', 'I': 'Ibsq', 'O': 'Olgb'},
    "Wdro": {'L': 'Ldro', 'F': 'Fdro', 'B': 'Bdsd', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vdrr', 'Q': 'Qdrr', 'X': 'Xdtr', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zdtr', 'I': 'Idtr', 'O': 'Odtr'},
    "Wdrt": {'L': 'Ldrt', 'F': 'Fdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "Wgrs": {'L': 'Lgrs', 'F': 'Fgrs', 'B': 'Bgrr', 'A': 'Agrs', 'C': 'Cgrs', 'N': 'Nsnw', 'Y': 'Ygsb', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dsqd', 'G': 'Gsqd', 'Z': 'Zgrs', 'I': 'Iice', 'O': 'Ofsl'},
    "Wrok": {'L': 'Lrok', 'F': 'Frok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ybtl', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xbtl', 'D': 'Ddkr', 'G': 'Gdkr', 'Z': 'Zbkl', 'I': 'Irbk', 'O': 'Ofst'},
    "Wsng": {'L': 'Ldrg', 'F': 'Fdrg', 'B': 'Bdrr', 'C': 'Cpos', 'N': 'Ngrs', 'Y': 'Ygsb', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xgsb', 'D': 'Dgrs', 'G': 'Ggrs', 'Z': 'Zdrg', 'I': 'Idki', 'O': 'Ofsl', 'A': 'Adrg'},
    "Wsnw": {'L': 'Lgrd', 'F': 'Fgrd', 'B': 'Bdrg', 'A': 'Agrd', 'C': 'Clvg', 'N': 'Nice', 'Y': 'Ygsb', 'V': 'Vgrt', 'Q': 'Qgrt', 'X': 'Xgsb', 'D': 'Dlav', 'G': 'Glav', 'Z': 'Zsan', 'I': 'Isnw', 'O': 'Ofst'},
    "Xblm": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bdrr', 'A': 'Avin', 'C': 'Cvin', 'N': 'Nrck', 'V': 'Vstp', 'Q': 'Qstp', 'Y': 'Yblm', 'D': 'Drds', 'G': 'Grds', 'Z': 'Ztil', 'I': 'Ibsq', 'O': 'Odkt'},
    "Xbtl": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'V': 'Vrck', 'Q': 'Qrck', 'Y': 'Ybtl', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zbks', 'I': 'Ibkb', 'O': 'Osmb'},
    "Xdrt": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'Y': 'Ydrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "Xdtr": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdsd', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'V': 'Vdrr', 'Q': 'Qdrr', 'Y': 'Ydtr', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zdrg', 'I': 'Idtr', 'O': 'Odtr'},
    "Xgsb": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'N': 'Nsnw', 'C': 'Cgrs', 'V': 'Vgrs', 'Q': 'Qgrs', 'Y': 'Ygsb', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofsl'},
    "Xhdg": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'N': 'Nice', 'C': 'Cgrs', 'V': 'Vgrs', 'Q': 'Qgrs', 'Y': 'Yhdg', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zsan', 'I': 'Iice', 'O': 'Ofst'},
    "Xrtl": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'V': 'Vrck', 'Q': 'Qrck', 'Y': 'Yrtl', 'D': 'Dsqd', 'G': 'Gsqd', 'Z': 'Ztil', 'I': 'Itbk', 'O': 'Olgb'},
    "Xsqd": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Nsnr', 'V': 'Vdrt', 'Q': 'Qdrt', 'Y': 'Ysqd', 'D': 'Dsqd', 'G': 'Gsqd', 'Z': 'Zbkl', 'I': 'Irbk', 'O': 'Osqt'},
    "Xwmb": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'V': 'Vrck', 'Q': 'Qrck', 'Y': 'Ywmb', 'D': 'Dgrs', 'G': 'Ggrs', 'Z': 'Ztil', 'I': 'Ibsq', 'O': 'Odkt'},
    "Yblm": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bdrr', 'A': 'Avin', 'C': 'Cvin', 'N': 'Nrck', 'V': 'Vstp', 'Q': 'Qstp', 'X': 'Xblm', 'D': 'Drds', 'G': 'Grds', 'Z': 'Ztil', 'I': 'Ibsq', 'O': 'Odkt'},
    "Ybtl": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xbtl', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zbks', 'I': 'Ibkb', 'O': 'Osmb'},
    "Ydrt": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "Ydtr": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdsd', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'V': 'Vdrr', 'Q': 'Qdrr', 'X': 'Xdtr', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zdtr', 'I': 'Idtr', 'O': 'Odtr'},
    "Ygsb": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'N': 'Ngrs', 'C': 'Cgrs', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xgsb', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofsl'},
    "Yhdg": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'N': 'Ngrs', 'C': 'Cgrs', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zsan', 'I': 'Iice', 'O': 'Ofst'},
    "Yrtl": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xrtl', 'D': 'Dsqd', 'G': 'Gsqd', 'Z': 'Ztil', 'I': 'Itbk', 'O': 'Olgb'},
    "Ysqd": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Nsnr', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xsqd', 'D': 'Dsqd', 'G': 'Gsqd', 'Z': 'Zbkl', 'I': 'Irbk', 'O': 'Osqt'},
    "Ywmb": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xwmb', 'D': 'Dgrs', 'G': 'Ggrs', 'Z': 'Ztil', 'I': 'Ibsq', 'O': 'Odkt'},
    "Zbkl": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ysqd', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xsqd', 'D': 'Drds', 'G': 'Grds', 'I': 'Irbk', 'O': 'Olgb'},
    "Zbks": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bdrr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ybtl', 'V': 'Vcbp', 'Q': 'Qcbp', 'X': 'Xbtl', 'D': 'Dbrk', 'G': 'Gbrk', 'I': 'Ibkb', 'O': 'Osmb'},
    "Zdrg": {'L': 'Ldrg', 'F': 'Fdrg', 'W': 'Wsng', 'B': 'Bdrg', 'A': 'Adrg', 'C': 'Clvg', 'N': 'Nice', 'Y': 'Ygsb', 'V': 'Vgrt', 'Q': 'Qgrt', 'X': 'Xgsb', 'D': 'Dgrs', 'G': 'Ggrs', 'I': 'Idtr', 'O': 'Ofsl'},
    "Zdrt": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'Y': 'Ydrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "Zdtr": {'L': 'Ldro', 'F': 'Fdro', 'W': 'Wdro', 'B': 'Bdsd', 'A': 'Adrd', 'C': 'Cdrd', 'N': 'Ndrd', 'Y': 'Ydtr', 'V': 'Vdrr', 'Q': 'Qdrr', 'X': 'Xdtr', 'D': 'Dbrk', 'G': 'Gbrk', 'I': 'Idtr', 'O': 'Odtr'},
    "Zgrs": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'C': 'Cgrs', 'N': 'Ngrs', 'Y': 'Ygsb', 'V': 'Vgrt', 'Q': 'Qgrt', 'X': 'Xgsb', 'D': 'Drds', 'G': 'Grds', 'I': 'Isnw', 'O': 'Ofsl'},
    "Zsan": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wsnw', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cpos', 'N': 'Nice', 'Y': 'Yhdg', 'V': 'Vcrp', 'Q': 'Qcrp', 'X': 'Xhdg', 'D': 'Dlav', 'G': 'Glav', 'I': 'Iice', 'O': 'Odtr'},
    "Ztil": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Yrtl', 'V': 'Vstp', 'Q': 'Qstp', 'X': 'Xrtl', 'D': 'Dgrs', 'G': 'Ggrs', 'I': 'Itbk', 'O': 'Osqt'},
    "Zvin": {'L': 'Lgrd', 'F': 'Fgrd', 'W': 'Wsnw', 'B': 'Bdsd', 'A': 'Agrd', 'C': 'Cvin', 'N': 'Nice', 'Y': 'Ygsb', 'V': 'Vgrt', 'Q': 'Qgrt', 'X': 'Xgsb', 'D': 'Drds', 'G': 'Grds', 'I': 'Isnw', 'O': 'Ofst'},
    "cAc1": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'C': 'Cgrs', 'N': 'Ngrs', 'Y': 'Yhdg', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dbrk', 'G': 'Gbrk', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofsl'},
    "cBc1": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'A': 'Agrs', 'C': 'Cgrs', 'N': 'Ngrs', 'Y': 'Yhdg', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dlvc', 'G': 'Glvc', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofsl'},
    "cBc2": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zsan', 'I': 'Idrt', 'O': 'Ofst'},
    "cCc1": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'N': 'Ngrs', 'Y': 'Yhdg', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dgrs', 'G': 'Ggrs', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofsl'},
    "cCc2": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "cDc1": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ysqd', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xsqd', 'G': 'Gsqd', 'Z': 'Zbkl', 'I': 'Itbk', 'O': 'Osqt'},
    "cDc2": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "cFc1": {'L': 'Lgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'C': 'Cgrs', 'N': 'Nsnw', 'Y': 'Ygsb', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dsqd', 'G': 'Gsqd', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofsl'},
    "cFc2": {'L': 'Ldrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "cGc1": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ysqd', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xsqd', 'D': 'Dsqd', 'Z': 'Zbkl', 'I': 'Itbk', 'O': 'Osqt'},
    "cGc2": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "cIc1": {'Z': 'Zgrs', 'O': 'Ofsl'},
    "cIc2": {'Z': 'Zbkl', 'O': 'Olgb'},
    "cJc1": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Nsnr', 'Y': 'Ysqd', 'V': 'Vdrt', 'Q': 'Qdrt', 'D': 'Dsqd', 'G': 'Gsqd', 'Z': 'Zbkl', 'I': 'Irbk', 'O': 'Osqt'},
    "cJc2": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'Y': 'Ydrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "cKc1": {'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "cKc2": {'Z': 'Ztil', 'I': 'Ibsq', 'O': 'Odkt'},
    "cLc1": {'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'C': 'Cgrs', 'N': 'Nsnw', 'Y': 'Ygsb', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dsqd', 'G': 'Gsqd', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofsl'},
    "cLc2": {'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "cNc1": {'L': 'Lgrs', 'F': 'Fgrs', 'W': 'Wgrs', 'B': 'Bgrr', 'A': 'Agrs', 'C': 'Clvg', 'Y': 'Yhdg', 'V': 'Vgrt', 'Q': 'Qgrt', 'X': 'Xhdg', 'D': 'Dlav', 'G': 'Glav', 'Z': 'Zsan', 'I': 'Isnw', 'O': 'Ofst'},
    "cNc2": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "cOc1": {'Z': 'Zdrt', 'I': 'Idrt', 'K': 'Kdrt'},
    "cOc2": {'Z': 'Zdtr', 'I': 'Idtr', 'K': 'Kdtr'},
    "cQc1": {'L': 'Lgrd', 'F': 'Fgrd', 'W': 'Wsnw', 'B': 'Bdrg', 'A': 'Agrd', 'C': 'Clvg', 'N': 'Nice', 'Y': 'Ygsb', 'V': 'Vgrt', 'X': 'Xgsb', 'D': 'Dlav', 'G': 'Glav', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofst'},
    "cQc2": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "cVc1": {'L': 'Lgrd', 'F': 'Fgrd', 'W': 'Wsnw', 'B': 'Bdrg', 'A': 'Agrd', 'C': 'Clvg', 'N': 'Nice', 'Y': 'Ygsb', 'Q': 'Qgrt', 'X': 'Xgsb', 'D': 'Dlav', 'G': 'Glav', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofst'},
    "cVc2": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "cWc1": {'L': 'Lgrd', 'F': 'Fgrd', 'B': 'Bdrg', 'A': 'Agrd', 'C': 'Clvg', 'N': 'Nice', 'Y': 'Ygsb', 'V': 'Vgrt', 'Q': 'Qgrt', 'X': 'Xgsb', 'D': 'Dlav', 'G': 'Glav', 'Z': 'Zsan', 'I': 'Iice', 'O': 'Ofst'},
    "cWc2": {'L': 'Lgrs', 'F': 'Fgrs', 'B': 'Bgrr', 'A': 'Agrs', 'C': 'Cgrs', 'N': 'Nsnw', 'Y': 'Ygsb', 'V': 'Vgrs', 'Q': 'Qgrs', 'X': 'Xhdg', 'D': 'Dsqd', 'G': 'Gsqd', 'Z': 'Zgrs', 'I': 'Isnw', 'O': 'Ofsl'},
    "cXc1": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Nsnr', 'Y': 'Ysqd', 'V': 'Vdrt', 'Q': 'Qdrt', 'D': 'Dsqd', 'G': 'Gsqd', 'Z': 'Zbkl', 'I': 'Irbk', 'O': 'Osqt'},
    "cXc2": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "cYc1": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Nsnr', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xsqd', 'D': 'Dsqd', 'G': 'Gsqd', 'Z': 'Zbkl', 'I': 'Irbk', 'O': 'Osqt'},
    "cYc2": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'Z': 'Zdrt', 'I': 'Idrt', 'O': 'Odrt'},
    "cZc1": {'L': 'Lrok', 'F': 'Frok', 'W': 'Wrok', 'B': 'Bflr', 'A': 'Arck', 'C': 'Crck', 'N': 'Nrck', 'Y': 'Ysqd', 'V': 'Vrck', 'Q': 'Qrck', 'X': 'Xsqd', 'D': 'Drds', 'G': 'Grds', 'I': 'Irbk', 'O': 'Olgb'},
    "cZc2": {'L': 'Ldrt', 'F': 'Fdrt', 'W': 'Wdrt', 'B': 'Bdsr', 'A': 'Adrt', 'C': 'Cdrt', 'N': 'Ndrt', 'Y': 'Ydrt', 'V': 'Vdrt', 'Q': 'Qdrt', 'X': 'Xdrt', 'D': 'Ddrt', 'G': 'Gdrt', 'I': 'Idrt', 'O': 'Odrt'},
}

# 悬崖 id → 崖底贴图（TerrainArt/CliffTypes.slk 的 groundTile 列，2026-09-17 实测导出）。
# 用途：apply_style 换风格时，悬崖索引不能按序号直搬（各风格表内顺序不同，
# 如 L=[CLdi,CLgr] 0泥1草 而 A=[CAgr,CAdi] 0草1泥），必须按语义换算：
# 源悬崖 id → groundTile → CONVERT 到目标风格地面 id → 反查目标风格悬崖表。
CLIFF_GROUND = {
    "CLdi": "Ldrt", "CLgr": "Lgrs",
    "CFdi": "Fdrt", "CFgr": "Fgrs",
    "CWgr": "Wgrs", "CWsn": "Wsnw",
    "CBde": "Bdsr", "CBgr": "Bgrr",
    "CNdi": "Ndrt", "CNsn": "Nsnw",
    "CAgr": "Agrs", "CAdi": "Adrt",
    "CCgr": "Cgrs", "CCdi": "Cdrt",
    "CYdi": "Ydrt", "CYsq": "Ysqd",
}
